import type { Metadata } from "next";
import { Oleo_Script_Swash_Caps, Open_Sans } from "next/font/google";
import "./globals.css";

const oleo = Oleo_Script_Swash_Caps({
  variable: "--oleo",
  subsets: ["latin"],
  weight: ['400'],
});
const open = Open_Sans({
  variable: "--open",
  subsets: ["latin"],
  weight: ['400'],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${oleo.variable} ${open.variable} font-sans `}>
      <body
        
        dir="rtl "
      >
        {children}
      </body>
    </html>
  );
}
